/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EvsdGovernor__factory } from './EvsdGovernor__factory.js';
export { EvsdToken__factory } from './EvsdToken__factory.js';